name: 365 Managed IT
favicon: null
layout_spectrum: 0.24225
typography_spectrum: 0.16900944313965738
title: Providing a Complete Suite of IT Solutions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#002764'
    - '#c0821d'
    - '#0071ac'
    - '#ff0000'
    - '#83bad7'
  brandStrength: 0.2739701922982931
  lightness: 0.47856474737636745
  saturation: 0.5374332573264837
  rhythmicContrast: 0.9911247051786631
purpose: []
